# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'monthly'
      day: 'saturday'
      time: '07:00'
      timezone: 'America/Chicago'
    labels:
      - 'npm'
      - 'dependabot'
    target-branch: 'main'
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: '-'
    commit-message:
      prefix: '⬆️ '
    groups:
      patch:
        update-types:
          - patch
      eslint:
        patterns:
          - '*eslint*'
        update-types:
          - 'minor'
      prettier:
        patterns:
          - '*prettier*'
        update-types:
          - 'minor'
      typescript:
        patterns:
          - '*typescript*'
          - tslib
        update-types:
          - 'minor'
      storybook:
        patterns:
          - '@storybook*'
          - storybook
        update-types:
          - 'minor'
      jest:
        patterns:
          - '*jest*'
          - '@testing-library/*'
        update-types:
          - 'minor'
      next:
        patterns:
          - next
          - 'next*'
          - '@vercel/*'
          - 'sharp'
          - 'server-only'
          - 'client-only'
        update-types:
          - 'minor'
      react:
        patterns:
          - react
          - react-dom
          - react*
          - sharp
        update-types:
          - 'minor'
