import throwError from '@helpers/throwError';
import { Overpass } from 'next/font/google';
import './globals.css';
import HomepageRecoilRoot from './homepageRecoilRoot';

const overpass = Overpass({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

const API_ENDPOINT =
	process.env.API_ENDPOINT ??
	throwError('API_ENDPOINT env variable not defined (should be "https://jsonplaceholder.typicode.com/todos/1")');

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	const response = await fetch(API_ENDPOINT);
	const user = await response.json();

	return (
		<html lang="en">
			<body className={overpass.className}>
				<HomepageRecoilRoot user={user}>{children}</HomepageRecoilRoot>
			</body>
		</html>
	);
}
